# .github/workflows/lint.yml

name: Lint and Format Code

on:
  push:
    branches:
      - main

jobs:     
  # This job runs on direct pushes to the main branch and creates a new PR with fixes.
  create-pr-for-main:
    name: "Create PR with fixes for main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install

      - name: Run Prettier to format code
        run: npm run format

      - name: Run ESLint to fix issues
        run: npm run lint:fix
        continue-on-error: true

      - name: Import GPG key and Configure Git
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request with signed commit
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: Auto-format and lint code"
          title: "Automated Code Formatting for Main Branch"
          body: |
            This PR was auto-generated by a GitHub Action to apply linting and formatting fixes to the `main` branch. Please review and merge.
          branch: "style-fixes/main-branch"
          base: main
          delete-branch: true
          committer: "github-actions[bot] <${{ steps.import_gpg.outputs.email }}>"
          author: "github-actions[bot] <${{ steps.import_gpg.outputs.email }}>"
